services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/conf/otel-collector-config.yml"]
    volumes:
      - ./configs/otel-collector/otel-collector-config.yml:/conf/otel-collector-config.yml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    environment:
      - "LOG_LEVEL=info"
    networks:
      - cdc-stream
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - cdc-stream
    volumes:
      - jaeger-data:/tmp/jaeger-data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
volumes:
  jaeger-data:
    driver: local
networks:
  cdc-stream:
    external: true